theme = "custom"

[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "error"
[editor]
end-of-line-diagnostics = "hint"

# "ui.cursor.insert" = { bg = "#ff0000" }
# mouse = false # until https://github.com/helix-editor/helix/issues/2102 is fixed
line-number = "relative"
indent-guides.render = true
bufferline = "multiple"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"


[keys.normal]
"backspace" = ":bclose"
"J" = "goto_next_paragraph"
"K" = "goto_prev_paragraph"
"C-j" = "join_selections"
"C-x" = "hsplit"
"C-y" = "vsplit"
"." = "vsplit"
g.S = ["split_selection_on_newline", ":sort", "keep_primary_selection"]
# "C-n" = "split_selection_on_newline"
"æ" = "flip_selections"
"C-e" = "repeat_last_motion"
"D" = "remove_primary_selection"
"}" = "rotate_selection_contents_forward"
"{" = "rotate_selection_contents_backward"
g."," = "@mimS, " # TODO: enter here
"C-p" = "goto_previous_buffer"
"C-n" = "goto_next_buffer"
"C-t" = ":tree-sitter-scopes"
"C-h" = ":tree-sitter-subtree"
"C-r" = ":tree-sitter-highlight-name"

"C-v" = "@vmiw*n"
# "C-v" = ["select_mode", "select_textobject_inner", "@w"]
# "C-D" = ["vmiw*n"]

[keys.normal.space]
"b" = "no_op"
"space" = "buffer_picker"

# https://github.com/helix-editor/helix/discussions/6421
B = ":sh blame %{buffer_name} %{cursor_line}" # Show blame information
U = ":sh blame --url-only %{cursor_line} %{buffer_name} | xargs -I{} xdg-open {}" # Open PR or commit url in browser

[keys.select]
"J" = "goto_next_paragraph"
"K" = "goto_prev_paragraph"
"C-j" = "join_selections"
"æ" = "flip_selections"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
newline = "¬"
nbsp = "~"
tab = "→"
